### PR TITLE
Added function isBoardFull to Tic.java.

### PR DESCRIPTION
**Pull request by brynhildurb12**
Added testIsBoardFullNo and testIsBoardFullYes to TicTest.java.

### CODE REVIEW

**Comment by rthor** [comment]
What do we need this function for? Some context would be great :)

**Comment by brynhildurb12** [comment]
This was thought to serve as a checking function. To see if we had a tie situation i.e the board is full and no winner.

**Comment by Heidaros13** [comment]
Suggestion: we could simplify the code if we use a counter with the IsWinner function.

**Comment by rthor** [comment]
@Heidaros13 :+1:  Let's do that, seems simpler and more easily modified and maintained down the road.

**Pull request closed without merging**
