### PR TITLE
Moved and deleted file due to duplication.

### PR DESCRIPTION
**Pull request by asabjorg**

### CODE REVIEW

**Comment by rthor** [comment]
The updates that you did to some of the files, are those due to code duplication?

**Comment by asabjorg** [comment]
No. Earlier we forgot to deleted original docs files when we were moving them to the right place, so we had duplicates of all the .md files and the readme file

**Comment by rthor** [comment]
Yeah I know, but you did some altering to the docs/ files—added some text. Is that something that had been changed before, just in the wrong location?

**Comment by asabjorg** [comment]
No just location.

**Comment by rthor** [comment]
Resolved in person:

> These edits are due to code duplication, i.e. files where updated in the wrong location.

**Comment by rthor** [comment]
LGTM

**Pull request merged**
